<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0-windows10.0.19041.0</TargetFramework><UseWinUI>true</UseWinUI><WindowsPackageType>None</WindowsPackageType><WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained></PropertyGroup>
  <ItemGroup>
    <Content Update="Assets/Fluent/*.svg" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Update="Assets/Fluent/LICENSE" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup><PackageReference Include="Microsoft.WindowsAppSDK" Version="2.5.1"/><ProjectReference Include="../Zheli.Platform/Zheli.Platform.csproj"/></ItemGroup>
</Project>
